"""
CARRILLO CERVANTES IVETTE ALEJANDRA
ESTRUCTURA DE DATOS Y ALGORITMOS - GRUPO 1
"""

def MinMax(L):
	a = len(L) # Se puso el valor de la lista aquí
	if len(L) == 1: # SI EL TAMAÑO DE LA LISTA ES 1
		return (L[0], L[0]) # TANTO EL VALOR MAXIMO COMO MINIMO, ES EL MISMO (PRIMER INDICE)
	elif len(L) == 2: # SI EL TAMAÑO DE LA LISTA ES 2
		if L[0] <= L[1]: # SI EL PRIMER INDICE ES MENOR O IGUAL QUE EL SEGUNDO
			return (L[0], L[1]) # EL VALOR MINIMO DE LA LISTA ES EL PRIMER INDICE Y EL MAXIMO EL SEGUNDO
		else: # SI NO SE CUMPLEN LAS CONDICIONES ANTERIORES, OSEA SI EL PRIMER INDICE ES MAYOR O IGUAL QUE EL SEGUNDO
			return (L[1], L[0]) # EL VALOR MINIMO DE LA LISTA ES EL SEGUNDO INDICE Y EL MAXIMO EL PRIMERO
	else: # SI EL TAMAÑO DE LA LISTA ES MAYOR QUE 2
		# len[L] <- calcula la cantidad de elementos en la lista
		mid = a / 2 # VARIABLE QUE ALMACENA LA MITAD DE LA LISTA
		# LLAMAMOS LA FUNCION (RECURSIVIDAD)
		(minL, maxL) = MinMax (L[:int(mid)])
		(minR, maxR) = MinMax (L[int(mid):])
		if minL <= minR: # SI EL VALOR MINIMO DE LA IZQUIERDA ES MENOR QUE EL VALOR MINIMO DE LA DERECHA
			min = minL # EL VALOR MIN SERA EL DE LA IZQUIERDA
		else: # EN CASO CONTRARIO
			min = minR # EL VALOR MINIMO SERA EL DE LA DERECHA
		if maxL >= maxR: # SI EL VALOR MAXIMO DE LA IZQUIERDA ES MAYOR QUE EL VALOR MAXIMO DE LA DERECHA
			max = maxL # EL VALOR MAXIMO SERA EL DE LA IZQUIERDA
		else: # EN CASO CONTRARIO
			max = maxR # EL CALOR MAXIMO SERA EL DE LA DERECHA
	return (min, max) # <- se corrijio la identación aquí
	# RETORNA EL VALOR MINIMO Y MAXIMO DE LA LISTA

def principal():
	
	# SE INICIALIZA UNA LISTA CON VARIOS ELEMENTOS
	lista = [3, 10, 32, 100, 4, 76, 45, 32, 17, 12, 1] 

	# SE LLAMA A LA FUNCIÓN "MinMax()", CUYO PARAMETRO ES LA LISTA INICIALIZADA
	minn, maxx = MinMax(lista) # LOS VALORES QUE RETORNA LA FUNCIÓN SE GUARDAN EN DOS VARIABLES DIFERENTES
	
	# SE IMPRIME LA LISTA Y LOS VALORES MINIMO, MAXIMO DE ELLA
	print('\nLista: ', lista) 
	print('Valor mínimo de la lista: ', minn)
	print('Valor máximo de la lista: ', maxx)

# SE LLAMA A LA FUNCION PRINCIPAL
principal()