typedef struct Cola Cola;

Cola crearCola(); // CREA UNA COLA
int isEmptyC(Cola); // VERIFICA SI LA COLA ESTA VACIA O ESTA LLENA, COMO NO SE HACE CAMBIO SE UTILIZA PASO POR VALOR
void encolar(Cola*,int); // AGREGA UN VALOR, COMO SE HACE CAMBIO, SE UTILIZA COMO PASO POR REFERENCIA, EL PRIMER PARAMETRO ES LA COLA QUE SE CREO Y EL SEGUNDO ES EL ENTERO QUE SE VA A AGREGAR
int desencolar(Cola*); // QUITA UN VALOR, IGUAL SE HARÁ PASO POR REFERENCIA YA QUE SE ESTA MODIFICANDO LA COLA, EL PARAMETRO ES EL APUNTADOR DE LA COLA
int first(Cola); // ACCEDEMOS A SU PRIMERO Y RETORNAMOS EL VALOR DEL ULTIMO ELEMENTO INGRESADO, COMO NO SE VA A MODIFICAR, UTILIZAMOS PASO POR VALOR



